# sensors
sensors:
  - touch: 0
  - orientation: 1
  - motion: 2
  - front camera: 3
  - back camera: 4
  - proximity: 5
  - microphone: 6

# ui
mainTablePath: 'assets/maintable.html'
borderMainTable: 0